# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosproj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AgoraRtcEngine_iOS', '4.2.3'
  # Pods for iosproj

  target 'iosprojTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosprojUITests' do
    # Pods for testing
  end

end
